### ISSUE TITLE
VaultPassword required?

### ISSUE THREAD

**Issue by AD-Wright** [AronMarinelli/bitwarden-secure-sync#12]
The linked page describing the use of the api key (https://bitwarden.com/help/personal-api-key/) seems to indicate that the API keys are all that is needed to manage the vault.  Why is there a required "VaultPassword" field?  Also, what is this VaultPassword field, is it the same as the Master Password?

**Comment by AronMarinelli** [comment]
The VaultPassword is required in order to access and unlock the items in your vault, and is indeed the same as the master password of your vault. As with the regular sign in process, the API key is solely used to access your account, and is seperate from the master password.

Please refer to the unlock section of the Bitwarden CLI documentation (https://bitwarden.com/help/cli/#unlock) to see how this process works in practice.
